import React, { useState } from 'react';
import styles from '../styles/pages/blog.module.scss';
import Link from 'next/link';
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

const Blog = () => {
   const blogArray = [
      {
         "title": "title1",
         "thumbImg": "/public/img/blogs/thumbs/F3_a.jpg",
         "bannerImg": "/public/img/blogs/banner/F3_a_United_Nations.jpg",
         "content": " qwerty",
         "url": "/blog"
      },
      {
         "title": "title2",
         "thumbImg": "/public/img/blogs/thumbs/F3_a.jpg",
         "bannerImg": "/public/img/blogs/banner/F3_a_United_Nations.jpg",
         "content": " ertyui",
         "url": "/blog"
      },
      {
         "title": "title3",
         "thumbImg": "/public/img/blogs/thumbs/F3_a.jpg",
         "bannerImg": "/public/img/blogs/banner/F3_a_United_Nations.jpg",
         "content": " xcvbn",
         "url": "/"
      }
   ]


   return (
      <div>
         <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Header />

         <main className={`${styles.blogPage}`}>

            <div className={`${styles.blogSection}`}>
               <div className="container">
                  <div className={`${styles.blogWrapp}`}>
                     {/* looping blog data here */}
                     {
                        blogArray.map(function (item, index) {
                           return (
                              <div className={`${styles.blogItem}`} key={index}>
                                 <div className={`${styles.blogImg}`}>
                                    <img src="/img/blogs/thumbs/F3_a.jpg" alt="" />
                                 </div>
                                 <h2 className={`${styles.blogTitle}`}>{item.title}</h2>
                                 <div className={`${styles.blogDescription}`}>{item.content}</div>
                                 <div className={`${styles.blogButton}`}><Link href={item.url}>Link
                                 </Link >
                                 </div>
                              </div>
                           )
                        })
                     }
                  </div>
               </div>
            </div>
         </main>
      </div>
   )
}

export default Blog