import React from 'react';
import styles from '../styles/pages/blog.module.scss';
import Link from 'next/link';
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

const blog = () => {
  return (
    <div>
        <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <Header /> */}
        
        <main>
            <div className={`${styles.blogSection}`}>
                <Link href="/data/about-html"><a><h2 className={`${styles.blogTitle}`}>JavaScript</h2></a></Link>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            </div>

            <div className={`${styles.blogSection}`}>
                <Link href="/blog">
                <h2 className={`${styles.blogTitle}`}>Next.js</h2>
                </Link>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            </div>

            <div className={`${styles.blogSection}`}>
                <Link href="/blog">
                <h2 className={`${styles.blogTitle}`}>HTML</h2>
                </Link>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            </div>

        </main>
    </div>
  )
}

export default blog