import styles from "../styles/pages/Home.module.scss";

//import components
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={`${styles.index_page}`}>
        <section className="banner_section">

          <img src="img/modern-living.png" alt="mordern living"/>

        </section>
      </main>
      <Footer />
    </div>
  );
}
